spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: feature_flag_remote_config
    redis:
      url: ${REDIS_URI}

secret:
  key: "TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V"